name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: header
        uses: lowlighter/metrics@latest
        with:
          filename: headre.svg
          base: header
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes