name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: polyglot, stargazer, deployer, member, maintainer, developer
          plugin_achievements_display: compact
          plugin_achievements_threshold: X

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.wakatime.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, languages-graphs
          plugin_wakatime_days: 365
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year